module.exports = (db, cb) => {
    db.define("user_details", {
        user_id: Number,
        profile_heading: String,
        first_name: String,
        middle_name: String,
        last_name: String,
        current_address: String,
        permanent_address: String,
        gender: String,
        pincode: Number,
        office_phone: Number,
        mobile_phone: Number,
        home_phone: Number,
        marital_status: String,
        passport_number: String,
        dob: Date,
        current_package: Number,
        website: String,
        country: String,
        state: String,
        city: String,
        facebook: String,
        linkedin: String,
        github: String,
        stackoverflow: String,
        created_by: Number,
        modified_by: Number,
        modified_at: Date,
        created_at: Date,
    });
  }
